version: "3.1"

services:
  db:
    image: mysql:8
    container_name: curbcutdb
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3308:3306
    volumes:
      - ./.data/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: curbcut
      MYSQL_USER: curbcutuser
      MYSQL_PASSWORD: curbcutpasswd
      MYSQL_ROOT_PASSWORD: curbcutpasswd

  # adminer:
  #   image: adminer
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080

  # redis:
  #   image: redis:6-alpine
  #   container_name: beeth_redis
  #   ports:
  #     - "6379:6379" # Main port
