# fly.toml file generated for hse-bocast on 2022-07-01T14:27:14+01:00

app = "hse-bocast"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[build.args]
  BP_KEEP_FILES = "files/*"

[env]
  CURBCUT_CAPTIONS_ENDPOINT = "https://hse-curbcut.fly.dev/caption"
  CURBCUT_SRT_PATH="./files"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
