import { Caption } from "@prisma/client";
import {
  // stringify as createSubtitles,
  stringifySync,
  Node,
} from "subtitle";

const captionsToNodes = (captions: Caption[], startAt: number): Node[] => {
  const sentences = captions.map<Node>((tr) => ({
    type: "cue",
    data: {
      start: Math.floor(Number(tr.timestampStart) - startAt),
      end: Math.floor(
        (Number(tr.timestampEnd) || Number(tr.timestampStart) + 3000) - startAt
      ),
      text: tr.text,
    },
  }));
  return [
    {
      type: "header",
      data: `WEBVTT - Subtitles generated by HSE, a LearnFWD product`,
    },
    ...sentences,
  ];
};

export const captionsToSrt = (captions: Caption[], startAt: number) => {
  const sentences = captionsToNodes(captions, startAt);
  const subs = stringifySync(sentences, { format: "SRT" });
  return subs;
};

export const captionsToWebVTT = (captions: Caption[], startAt: number) => {
  const sentences = captionsToNodes(captions, startAt);
  const subs = stringifySync(sentences, { format: "WebVTT" });
  return subs;
};
