name: Fly - Server production
on:
  push:
    branches:
      - production
    paths:
      - "services/bo-cast/**"
      - '.github/workflows/deploy-bo-cast-fly-prod.yaml'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@1.1
        env:
          FLY_PROJECT_PATH: services/bo-cast
        with:
          args: "deploy"
