name: Bo-Cast Go Binary Release

on:
  push:
    paths:
      - 'services/bo-cast/**'
      - '.github/workflows/publish-bo-cast-release.yaml'

defaults:
  run:
    shell: bash
    working-directory: services/bo-cast

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "386"
            goos: linux
          - goarch: "386"
            goos: windows
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.29
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.13.1.linux-amd64.tar.gz"
        project_path: "."
        binary_name: "bo-cast"
